import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      fontFamily: {
        sans: ["'Manrope'", "system-ui", "-apple-system", "'Segoe UI'", "Roboto", "sans-serif"],
        mono: ["ui-monospace", "'SF Mono'", "Menlo", "Consolas", "monospace"],
      },
      fontSize: {
        xs: ["0.875rem", { lineHeight: "1.4" }],    // 14px supporting text
        sm: ["0.875rem", { lineHeight: "1.4" }],    // 14px supporting text
        base: ["1rem", { lineHeight: "1.5" }],       // 16px base body copy
        lg: ["1.125rem", { lineHeight: "1.3" }],    // 18px emphasis / headings
        xl: ["1.125rem", { lineHeight: "1.3" }],    // 18px emphasis / headings
        "2xl": ["1.5rem", { lineHeight: "1.2" }],   // 24px hero exception
        "3xl": ["1.5rem", { lineHeight: "1.2" }],   // 24px clamped hero
        "4xl": ["1.5rem", { lineHeight: "1.2" }],   // 24px clamped hero
        "5xl": ["1.5rem", { lineHeight: "1.2" }],   // 24px clamped hero
      },
      colors: {
        // Base design system tokens
        primary: {
          DEFAULT: "var(--color-primary)",
          foreground: "var(--color-secondary)",
        },
        secondary: {
          DEFAULT: "var(--color-secondary)",
          foreground: "var(--color-primary)",
        },
        tertiary: {
          DEFAULT: "var(--color-tertiary)",
          foreground: "var(--color-on-tertiary)",
        },
        accent: {
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-on-accent)",
        },
        border: "var(--border-color)",
        input: "var(--surface-card)",
        ring: "var(--color-accent)",
        background: "var(--color-primary)",
        foreground: "var(--color-secondary)",
        card: {
          DEFAULT: "var(--surface-card)",
          foreground: "var(--color-secondary)",
        },
        popover: {
          DEFAULT: "var(--surface-card)",
          foreground: "var(--color-secondary)",
        },
        muted: {
          DEFAULT: "var(--surface-card-subtle)",
          foreground: "var(--text-muted)",
        },
        destructive: {
          DEFAULT: "var(--color-accent)",
          foreground: "var(--color-on-accent)",
        },

        // Backward-compatible semantic namespace mapped strictly to the 4 tokens
        st: {
          primary: "var(--color-primary)",
          secondary: "var(--color-secondary)",
          tertiary: "var(--color-tertiary)",
          accent: "var(--color-accent)",
          surface: "var(--surface-card)",
          border: "var(--border-color)",
        },

        // Slate, Zinc, Gray, Neutral mapped to Primary / Card / Secondary derivatives
        slate: {
          50: "var(--color-secondary)",
          100: "var(--text-primary)",
          200: "var(--text-secondary)",
          300: "var(--text-secondary)",
          400: "var(--text-muted)",
          500: "var(--text-muted)",
          600: "var(--border-color)",
          700: "var(--border-color)",
          800: "var(--surface-card-subtle)",
          900: "var(--surface-card)",
          950: "var(--color-primary)",
        },
        zinc: {
          50: "var(--color-secondary)",
          100: "var(--text-primary)",
          200: "var(--text-secondary)",
          300: "var(--text-secondary)",
          400: "var(--text-muted)",
          500: "var(--text-muted)",
          600: "var(--border-color)",
          700: "var(--border-color)",
          800: "var(--surface-card-subtle)",
          900: "var(--surface-card)",
          950: "var(--color-primary)",
        },
        gray: {
          50: "var(--color-secondary)",
          100: "var(--text-primary)",
          200: "var(--text-secondary)",
          300: "var(--text-secondary)",
          400: "var(--text-muted)",
          500: "var(--text-muted)",
          600: "var(--border-color)",
          700: "var(--border-color)",
          800: "var(--surface-card-subtle)",
          900: "var(--surface-card)",
          950: "var(--color-primary)",
        },

        // Emerald, Green, Teal, Cyan mapped strictly to Tertiary
        emerald: {
          DEFAULT: "var(--color-tertiary)",
          50: "var(--color-tertiary)",
          100: "var(--color-tertiary)",
          200: "var(--color-tertiary)",
          300: "var(--color-tertiary)",
          400: "var(--color-tertiary)",
          500: "var(--color-tertiary)",
          600: "var(--color-tertiary)",
          700: "var(--color-tertiary)",
          800: "var(--color-tertiary)",
          900: "var(--color-tertiary)",
          950: "var(--color-tertiary)",
        },
        teal: {
          DEFAULT: "var(--color-tertiary)",
          50: "var(--color-tertiary)",
          100: "var(--color-tertiary)",
          200: "var(--color-tertiary)",
          300: "var(--color-tertiary)",
          400: "var(--color-tertiary)",
          500: "var(--color-tertiary)",
          600: "var(--color-tertiary)",
          700: "var(--color-tertiary)",
          800: "var(--color-tertiary)",
          900: "var(--color-tertiary)",
          950: "var(--color-tertiary)",
        },
        cyan: {
          DEFAULT: "var(--color-tertiary)",
          50: "var(--color-tertiary)",
          100: "var(--color-tertiary)",
          200: "var(--color-tertiary)",
          300: "var(--color-tertiary)",
          400: "var(--color-tertiary)",
          500: "var(--color-tertiary)",
          600: "var(--color-tertiary)",
          700: "var(--color-tertiary)",
          800: "var(--color-tertiary)",
          900: "var(--color-tertiary)",
          950: "var(--color-tertiary)",
        },

        // Amber, Yellow, Red, Rose, Orange mapped strictly to Accent
        amber: {
          DEFAULT: "var(--color-accent)",
          50: "var(--color-accent)",
          100: "var(--color-accent)",
          200: "var(--color-accent)",
          300: "var(--color-accent)",
          400: "var(--color-accent)",
          500: "var(--color-accent)",
          600: "var(--color-accent)",
          700: "var(--color-accent)",
          800: "var(--color-accent)",
          900: "var(--color-accent)",
          950: "var(--color-accent)",
        },
        yellow: {
          DEFAULT: "var(--color-accent)",
          50: "var(--color-accent)",
          100: "var(--color-accent)",
          200: "var(--color-accent)",
          300: "var(--color-accent)",
          400: "var(--color-accent)",
          500: "var(--color-accent)",
          600: "var(--color-accent)",
          700: "var(--color-accent)",
          800: "var(--color-accent)",
          900: "var(--color-accent)",
          950: "var(--color-accent)",
        },
        red: {
          DEFAULT: "var(--color-accent)",
          50: "var(--color-accent)",
          100: "var(--color-accent)",
          200: "var(--color-accent)",
          300: "var(--color-accent)",
          400: "var(--color-accent)",
          500: "var(--color-accent)",
          600: "var(--color-accent)",
          700: "var(--color-accent)",
          800: "var(--color-accent)",
          900: "var(--color-accent)",
          950: "var(--color-accent)",
        },
        rose: {
          DEFAULT: "var(--color-accent)",
          50: "var(--color-accent)",
          100: "var(--color-accent)",
          200: "var(--color-accent)",
          300: "var(--color-accent)",
          400: "var(--color-accent)",
          500: "var(--color-accent)",
          600: "var(--color-accent)",
          700: "var(--color-accent)",
          800: "var(--color-accent)",
          900: "var(--color-accent)",
          950: "var(--color-accent)",
        },
        orange: {
          DEFAULT: "var(--color-accent)",
          50: "var(--color-accent)",
          100: "var(--color-accent)",
          200: "var(--color-accent)",
          300: "var(--color-accent)",
          400: "var(--color-accent)",
          500: "var(--color-accent)",
          600: "var(--color-accent)",
          700: "var(--color-accent)",
          800: "var(--color-accent)",
          900: "var(--color-accent)",
          950: "var(--color-accent)",
        },

        // Blue, Indigo, Purple mapped strictly to Tertiary
        blue: {
          DEFAULT: "var(--color-tertiary)",
          50: "var(--color-tertiary)",
          100: "var(--color-tertiary)",
          200: "var(--color-tertiary)",
          300: "var(--color-tertiary)",
          400: "var(--color-tertiary)",
          500: "var(--color-tertiary)",
          600: "var(--color-tertiary)",
          700: "var(--color-tertiary)",
          800: "var(--color-tertiary)",
          900: "var(--color-tertiary)",
          950: "var(--color-tertiary)",
        },
        indigo: {
          DEFAULT: "var(--color-tertiary)",
          50: "var(--color-tertiary)",
          100: "var(--color-tertiary)",
          200: "var(--color-tertiary)",
          300: "var(--color-tertiary)",
          400: "var(--color-tertiary)",
          500: "var(--color-tertiary)",
          600: "var(--color-tertiary)",
          700: "var(--color-tertiary)",
          800: "var(--color-tertiary)",
          900: "var(--color-tertiary)",
          950: "var(--color-tertiary)",
        },
        purple: {
          DEFAULT: "var(--color-tertiary)",
          50: "var(--color-tertiary)",
          100: "var(--color-tertiary)",
          200: "var(--color-tertiary)",
          300: "var(--color-tertiary)",
          400: "var(--color-tertiary)",
          500: "var(--color-tertiary)",
          600: "var(--color-tertiary)",
          700: "var(--color-tertiary)",
          800: "var(--color-tertiary)",
          900: "var(--color-tertiary)",
          950: "var(--color-tertiary)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        pulseGlow: {
          "0%, 100%": { opacity: "1", filter: "drop-shadow(0 0 12px hsla(182, 80%, 20%, 0.4))" },
          "50%": { opacity: "0.7", filter: "drop-shadow(0 0 4px hsla(182, 80%, 20%, 0.2))" },
        },
        shimmer: {
          "100%": { transform: "translateX(100%)" },
        },
        fadeIn: {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        pulseGlow: "pulseGlow 2.5s ease-in-out infinite",
        shimmer: "shimmer 2s infinite",
        fadeIn: "fadeIn 0.3s ease-out",
      },
    },
  },
  plugins: [],
};
export default config;
